### ISSUE TITLE
NullPointerException caused by async connect/disconnect processing

### ISSUE THREAD

**Issue by andrew-tpz** [moquette-io/moquette#553] opened 2020-11-19 13:05 UTC
### Expected behavior
Session is not removed by handleConnectionLost if new session is already reopened

### Actual behavior
1. handleConnectionLost starts
2. processConnect starts and reopen session
3. handleConnectionLost continues and removes session
4. PostOffice.flushInFlight fails to use session

### Steps to reproduce
1. Run broker
2. Use clean session=true in mqtt-client
3. Start and stop mqtt-client several times. Try to do pause between stop and start as short as possible.
P.S. It seems like one more mqtt-client connected permanently gives better chance to reproduce.

### Minimal yet complete reproducer code (or URL to code) or complete log file
I added extra logging to catch the problem
```
14:59:39.254 [nioEventLoopGroup-3-6] io.moquette.broker.SessionRegistry - retrieve session OK by handleConnectionLost

14:59:39.254 [nioEventLoopGroup-3-7] io.moquette.broker.MQTTConnection  - processConnect started
14:59:39.254 [nioEventLoopGroup-3-7] io.moquette.broker.SessionRegistry - NEW SESSION
14:59:39.255 [nioEventLoopGroup-3-7] io.moquette.broker.SessionRegistry - REOPEN SESSION

14:59:39.255 [nioEventLoopGroup-3-6] io.moquette.broker.SessionRegistry - remove session by handleConnectionLost

14:59:39.255 [nioEventLoopGroup-3-7] io.moquette.broker.MQTTConnection  - processConnect ACK started
14:59:39.257 [nioEventLoopGroup-3-7] io.moquette.broker.MQTTConnection  - processConnect ACK end with true
14:59:39.257 [nioEventLoopGroup-3-7] io.moquette.broker.SessionRegistry - retrieve session NULL by flushInFlight

14:59:39.257 [nioEventLoopGroup-3-7] io.moquette.broker.NewNettyMQTTHandler  - Unexpected exception while processing MQTT message. Closing Netty channel. CId=
 java.lang.NullPointerException: Attempt to invoke virtual method 'void io.moquette.broker.Session.flushAllQueuedMessages()' on a null object reference
     at io.moquette.broker.PostOffice.flushInFlight(PostOffice.java:319)
     at io.moquette.broker.MQTTConnection.readCompleted(MQTTConnection.java:536)
     at io.moquette.broker.NewNettyMQTTHandler.channelReadComplete(NewNettyMQTTHandler.java:76)
```
### Moquette MQTT version
0.12.1, master 4665c5e

### JVM version (e.g. `java -version`)
1.8

**Comment by andsel** [comment] 2020-12-05 10:49
@andrew-tpz I've some questions, to recreate a reproducible test.
- Does you client connect and then exit without an close ?
- Do you have multiple client instances that uses the same clientId?

**Comment by andsel** [comment] 2020-12-05 11:34
I think that, supposing 2 instances of the same client with same client Id and clean session true, trying to connect to the broker generate the crash as:

|    | already connected client | new connecting client  |
|----|---------------|---|
| t1 | is CONNECTED  |   |
| t2 |               | process connect and find existing client, so close it https://github.com/moquette-io/moquette/blob/d8a59f135b2cf0896e04f6f02483b0841920fe60/broker/src/main/java/io/moquette/broker/SessionRegistry.java#L148  |
| t3 | the connection is notified of closing, https://github.com/moquette-io/moquette/blob/d8a59f135b2cf0896e04f6f02483b0841920fe60/broker/src/main/java/io/moquette/broker/MQTTConnection.java#L279  |
| t4 |               | replace the old session with new one https://github.com/moquette-io/moquette/blob/d8a59f135b2cf0896e04f6f02483b0841920fe60/broker/src/main/java/io/moquette/broker/SessionRegistry.java#L155 |   |  
| t5 | removes the session from registry https://github.com/moquette-io/moquette/blob/d8a59f135b2cf0896e04f6f02483b0841920fe60/broker/src/main/java/io/moquette/broker/MQTTConnection.java#L290  |   |   |  
| t6 |               | complete the connect flushing the CONNACK  |   |  
| t7 |               | receive the readComplete notification https://github.com/moquette-io/moquette/blob/d8a59f135b2cf0896e04f6f02483b0841920fe60/broker/src/main/java/io/moquette/broker/MQTTConnection.java#L532 which retrieve the session without checking it's valid and crash with NPE  |   |  

The problem is not the missed null check, but the interference of the `already connected client` that doesn't check the status of Session in registry, or if another client is in his connection sequence

**Comment by andrew-tpz** [comment] 2020-12-07 06:54
>     * Does you client connect and then exit without an close ?
Client connects on app start and I close it immediately by Alt+F4 (on Windows). So, time gap between start and stop is fractions of second. I can't say if it have time to close gracefully.

>     * Do you have multiple client instances that uses the same clientId?
No, but I start and close one client many times so quickly, that sometimes broker got "connected" event while it is processing previous "disconnected" event. It's kind of stress test, to catch the problem.

**Comment by andrew-tpz** [comment] 2020-12-21 10:15
The error now appears very rarely. However, I've got it once, but can't reproduce.
```
 E/i.m.b.NewNettyMQTTHandler: [nioEventLoopGroup-5-5] Error processing protocol message: CONNECTjava.lang.NullPointerException: Attempt to invoke virtual method 'boolean io.moquette.broker.Session.disconnected()' on a null object reference
        at io.moquette.broker.SessionRegistry.reopenExistingSession(SessionRegistry.java:119)
        at io.moquette.broker.SessionRegistry.createOrReopenSession(SessionRegistry.java:109)
        at io.moquette.broker.MQTTConnection.processConnect(MQTTConnection.java:168)
        at io.moquette.broker.MQTTConnection.handleMessage(MQTTConnection.java:69)
        at io.moquette.broker.NewNettyMQTTHandler.channelRead(NewNettyMQTTHandler.java:58)

```

**Comment by andsel** [comment] 2020-12-26 09:28
I think this problem is due to a check https://github.com/moquette-io/moquette/blob/08cc8ce1b885990b86411a96d2b62f71b6b5b429/broker/src/main/java/io/moquette/broker/SessionRegistry.java#L93 separed by from the retrieval of what's checked https://github.com/moquette-io/moquette/blob/08cc8ce1b885990b86411a96d2b62f71b6b5b429/broker/src/main/java/io/moquette/broker/SessionRegistry.java#L117, and the executing thread is interrupted in the middle, while the other client is disconnecting and removing the session in the middle of the two statements

**Comment by andsel** [comment] 2020-12-26 17:13
Hi @andrew-tpz  could you try the PR #561 and let me know if it fixes this, I think I caught the problem

**Comment by andrew-tpz** [comment] 2020-12-28 09:59
Hi @andsel, everything seems to be ok! Thanks!

**Closed as completed** 2020-12-28 10:03 UTC
Labels: bug
