### ISSUE TITLE
m_persistentMessageStore.remove(clientID)

### ISSUE THREAD

**Issue by myqhit** [moquette-io/moquette#200] opened 2016-08-12 07:44 UTC
![image](https://cloud.githubusercontent.com/assets/2512795/17615803/27650f28-60a3-11e6-999b-97052f5b3a55.png)
 sorry I'm also confused at code dropMessagesInSession,I find where you put the message in the m_persistentMessageStore, the code is above , the key in m_persistentMessageStore map is guid,so you remove message from the m_persistentMessageStore should use guid,not the clientId, am I right,
please don't  force closed the issue.

**Comment by peacecoder** [comment] 2016-08-29 08:27
yes, I think it there is a bug here. According to the overall logic and the comment of m_persistentMessageStore, it is the map of guid to message, rather then clientId to message. dropMessagesInSession method is wrong.

https://github.com/andsel/moquette/blob/master/broker/src/main/java/io/moquette/spi/persistence/MapDBMessagesStore.java#L100-L104

![image](https://cloud.githubusercontent.com/assets/10008870/18045373/2879e2a2-6e05-11e6-8cdb-24c17bbd6804.png)

**Comment by windbender** [comment] 2016-08-30 02:13
I've got a situation where the mapdb file appears to grow somewhat continuously.  This particular problem COULD be the source of it.  I've been meaning to dump the file to understand it more clearly.  This may be the excuse I need.

**Comment by windbender** [comment] 2016-08-30 02:14
Also could this be a duplicate of #193   or at least related ?

**Comment by andsel** [comment] 2016-08-30 06:23
Yes it's the same as #193, I keep this open... I'll fix it in next days

**Comment by myqhit** [comment] 2016-09-07 05:30
thank you all,I only reading the code to study and found this problem,some time maybe my problem,thank you for all help.

**Comment by myqhit** [comment] 2016-09-07 06:33
same as https://github.com/andsel/moquette/issues/198,I issue this problem 3 times

**Comment by windbender** [comment] 2016-09-08 06:23
We should leave at least one of 193, 198, or 200  OPEN  since the bug still exists.  I would suggest 200 since  that is what andsel is tracking

**Comment by andsel** [comment] 2016-09-11 14:54
I reopen because it's not fixed yet

**Comment by andsel** [comment] 2016-09-23 09:52
Solved, I've introduced a reference counter of stored messages just to remove once it hit 0 refs.

**Closed as completed by andsel** 2016-09-23 09:52 UTC
Labels: bug
