### ISSUE TITLE
Problem with Will message

### ISSUE THREAD

**Issue by PaoloFi** [moquette-io/moquette#16] opened 2015-02-19 19:18 UTC
Hi,
my problem is about sending the will message. When I simulate a  lost connection, I have the following error:

2015-02-19 20:15:15,476 INFO  ProtocolProcessor  - Lost connection with client <0.0.1>
2015-02-19 20:15:15,477 INFO  ProtocolProcessor  - Publish received from clientID <0.0.1> on topic <topic/diagnosticServer> with QoS EXACTLY_ONCE
feb 19, 2015 8:15:15 PM com.lmax.disruptor.FatalExceptionHandler handleEventException
GRAVE: Exception processing: 5 org.eclipse.moquette.spi.impl.ValueEvent@149e8424
java.lang.NullPointerException
    at org.eclipse.moquette.spi.impl.events.PublishEvent.<init>(PublishEvent.java:44)
    at org.eclipse.moquette.spi.impl.ProtocolProcessor.processPublish(ProtocolProcessor.java:301)
    at org.eclipse.moquette.spi.impl.ProtocolProcessor.processPublish(ProtocolProcessor.java:339)
    at org.eclipse.moquette.spi.impl.ProtocolProcessor.processConnectionLost(ProtocolProcessor.java:551)
    at org.eclipse.moquette.spi.impl.SimpleMessaging.onEvent(SimpleMessaging.java:146)
    at org.eclipse.moquette.spi.impl.SimpleMessaging.onEvent(SimpleMessaging.java:50)
    at com.lmax.disruptor.BatchEventProcessor.run(BatchEventProcessor.java:128)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
    at java.lang.Thread.run(Thread.java:745)

Exception in thread "pool-1-thread-1" java.lang.RuntimeException: java.lang.NullPointerException
    at com.lmax.disruptor.FatalExceptionHandler.handleEventException(FatalExceptionHandler.java:45)
    at com.lmax.disruptor.BatchEventProcessor.run(BatchEventProcessor.java:147)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
    at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.NullPointerException
    at org.eclipse.moquette.spi.impl.events.PublishEvent.<init>(PublishEvent.java:44)
    at org.eclipse.moquette.spi.impl.ProtocolProcessor.processPublish(ProtocolProcessor.java:301)
    at org.eclipse.moquette.spi.impl.ProtocolProcessor.processPublish(ProtocolProcessor.java:339)
    at org.eclipse.moquette.spi.impl.ProtocolProcessor.processConnectionLost(ProtocolProcessor.java:551)
    at org.eclipse.moquette.spi.impl.SimpleMessaging.onEvent(SimpleMessaging.java:146)
    at org.eclipse.moquette.spi.impl.SimpleMessaging.onEvent(SimpleMessaging.java:50)
    at com.lmax.disruptor.BatchEventProcessor.run(BatchEventProcessor.java:128)
    ... 3 more

This is the client side code:

client = new MqttClient(broker, clientId, persistence);
MqttConnectOptions connOpts = new MqttConnectOptions();
connOpts.setCleanSession(true);
connOpts.setWill(dgnServerTopic, my_message.getBytes(), 2, true);
client.setCallback(this);
client.connect(connOpts);

**Comment by PaoloFi** [comment] 2015-02-25 12:43
I have tested that there are no problems if I set Will QoS = 0. 
The problem concerns the lines 295 for QoS = 1 and 301 for QoS = 2 (org.eclipse.moquette.spi.impl.ProtocolProcessor.java) . When the method "processPublish" ( line 339 ) is called,  MessageId = null, and this creates errors later.
Is the implementation designed to use QoS 1 , 2 on the will message?

**Comment by andsel** [comment] 2015-02-25 20:43
Yes this version support QoS1 and 2, if not it's a bug

**Comment by PaoloFi** [comment] 2015-02-26 10:31
Hi andsel,
you can find below a patch to manage Will messages also with QoS 1 and 2. Finally I avoid to call all the MQTT publisher notification for QoS 1 and 2 because in case of Will message I suppose that the reference publisher is offline. So I just send the Will message with the correct QoS to the subscribers and retain the message if retain flag is enabled.
Best Regards,

Paolo

<pre>
*** moquette-master/broker/src/main/java/org/eclipse/moquette/spi/impl/ProtocolProcessor.java   2015-02-24 23:38:05.000000000 +0100
--- ProtocolProcessor.java  2015-02-26 11:05:38.312029174 +0100
***************
*** 336,342 ****
          final AbstractMessage.QOSType qos = will.getQos();
          final ByteBuffer message = will.getPayload();
          boolean retain = will.isRetained();
!         processPublish(clientID, topic, qos, message, retain, null);
      }
      
      /**
--- 336,351 ----
          final AbstractMessage.QOSType qos = will.getQos();
          final ByteBuffer message = will.getPayload();
          boolean retain = will.isRetained();
!         publish2Subscribers(topic, qos, message, retain, null);
!         
!         if (retain) {
!             if (qos == AbstractMessage.QOSType.MOST_ONE) {
!                 //QoS == 0 && retain => clean old retained 
!                 m_messagesStore.cleanRetained(topic);
!             } else {
!                 m_messagesStore.storeRetained(topic, message, qos);
!             }
!         }
      }
      
      /**
</pre>

**Comment by andsel** [comment] 2015-03-02 21:53
Ciao Paolo,
I've take a look to the patch, but in this way you miss the storing of the in flight messages to the subscriber, and also the generation of a valid messageID. The core of the problem is that at line 340 of the ProtocolProcessor I mistakely invoke the processPublish with messagedID param to null also for QoS1 and QoS2 messages

**Comment by andsel** [comment] 2015-03-12 07:26
The fix has highlighted a problem in packet identifiers generation that has been fixed with commit 4195b0d62c582e1e48e689d2d3c63a7b54529f42

**Closed as completed by andsel** 2015-03-12 07:26 UTC
