### ISSUE TITLE
Npe in ClasspathConfig

### ISSUE THREAD

**Issue by kuzp** [moquette-io/moquette#170] opened 2016-04-27 23:39 UTC
```
ClasspathConfig cc = new ClasspathConfig();
```

produces npe due to `m_properties` field is [used](https://github.com/andsel/moquette/blob/master/broker/src/main/java/io/moquette/server/config/ClasspathConfig.java#L46) before get [initialized](https://github.com/andsel/moquette/blob/master/broker/src/main/java/io/moquette/server/config/ClasspathConfig.java#L52)

**Comment by windbender** [comment] 2016-05-06 17:30
Just noticed this as a duplicate of my #175.   I think it would be healthiest to close this as duplicate since I've indicated several possible solutions in #175.

**Comment by andsel** [comment] 2016-05-07 17:22
This topic is treated better in #175, so I close it, but refer to the other issue

**Closed as completed by andsel** 2016-05-07 17:22 UTC
