### ISSUE TITLE
Client re-connect get processed before previous connection loss is detected

### ISSUE THREAD

**Issue by whizzosoftware** [moquette-io/moquette#99] opened 2015-09-18 04:03 UTC
I'm seeing a problem in moquette 0.7 where a sudden reconnect of a client will cause an exception to be thrown when moquette tries to dispatch a published message to it. 

What appears to be happening is the CONNECT event for the new connection is processed before the LOST CONNECTION event for the previous connection. The new connection event is processed successfully and then the LOST CONNECTION event is processed on the next disruptor iteration which deletes the ConnectionDescription in the cache. When the broker attempts to publish to the client (which is still valid and connected), the ConnectionDescription is no longer in the cache and the following exception is thrown:

Serious error processing the message 

```
org.eclipse.moquette.proto.messages.PublishMessage@25c07562 for session [clientID: Hobson Hub]org.eclipse.moquette.server.netty.NettyChannel@7e5a884a","exception":"java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
at org.eclipse.moquette.spi.impl.AnnotationSupport.dispatch(AnnotationSupport.java:66) 
at org.eclipse.moquette.spi.impl.SimpleMessaging.onEvent(SimpleMessaging.java:173) 
at org.eclipse.moquette.spi.impl.SimpleMessaging.onEvent(SimpleMessaging.java:63)
 at com.lmax.disruptor.BatchEventProcessor.run(BatchEventProcessor.java:128)
 at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145) 
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615) 
at java.lang.Thread.run(Thread.java:745)\nCaused by: java.lang.reflect.InvocationTargetException: null tat sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) 
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
 at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) 
at java.lang.reflect.Method.invoke(Method.java:606) 
at org.eclipse.moquette.spi.impl.AnnotationSupport.dispatch(AnnotationSupport.java:64) ... 6 common frames omitted 
Caused by: java.lang.RuntimeException: Can't find a ConnectionDescriptor for client <sensor1> in cache <{Hobson Hub=ConnectionDescriptor{m_clientID=Hobson Hub, m_cleanSession=true}}> 
at org.eclipse.moquette.spi.impl.ProtocolProcessor.sendPublish(ProtocolProcessor.java:439) 
at org.eclipse.moquette.spi.impl.ProtocolProcessor.forward2Subscribers(ProtocolProcessor.java:388) 
at org.eclipse.moquette.spi.impl.ProtocolProcessor.executePublish(ProtocolProcessor.java:317) 
at org.eclipse.moquette.spi.impl.ProtocolProcessor.processPublish(ProtocolProcessor.java:301)
... 11 common frames omitted\n
```

**Comment by andsel** [comment] 2015-09-22 14:02
Hi @whizzosoftware  do you have the complete log to investigate all the messages arrived? The exception just display the error, there is a way to reproduce it?

**Comment by andsel** [comment] 2015-09-23 09:39
Hi probably this is the same error in issue #79, fixed in current master. Essentially the writes operation on DB was really slow due to an overuse of commit() operation, now is fixed with a commit window (like mosquitto does). Please could you re-test with current master?

**Comment by andsel** [comment] 2015-10-10 17:33
No answer, and the code base changed removing the ring buffer, so I close the issue.

 Andrea

**Closed as completed by andsel** 2015-10-10 17:33 UTC
